version: "3.8"
services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dev
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
  backend:
    image: node:latest
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm run start"
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/dev
volumes:
  db-data: